name: Python Tests


on: [ push ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          export JAVA_HOMO=$JAVA_HOME
          pytest ./tests --alluredir=allure-results --disable-warnings
        #continue-on-error: True

      - name: Run Coverage
        if: $(( always() ))
        run: |
          python -m packages.notofier.bot.py

      - name: Archive Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1
  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate report
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Download Allure
        run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.32.0/allure-2.32.0.tgz && sudo tar -xvzf allure-2.32.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.32.0/bin/allure /usr/bin/allure
      - name: Download Allure results
        uses: actions/download-artifact@v4
      - name: Generate Allure report
        run: allure generate -c  allure-results -o _site
      - name: Store report
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site
          retention-days: 1
  publish_report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Publish report
    steps:
      - name: Download Allure results
        uses: actions/download-artifact@v4
      - name: Upload Allure report
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to Guthub pages
        id: deployment
        uses: actions/deploy-pages@v4
      - run: echo "https://ichobotov.github.io/dm_api_tests/"










